### PR TITLE
github actions

### PR DESCRIPTION
**Pull request by tschm**
Use a bot to keep your github actions up-to-date

### CODE REVIEW

**Comment by Caceresenzo** [comment]
Hello,

Thanks for you pull request.

Is it because we use old version of `actions/checkout` for example?

**Comment by Caceresenzo** [comment]
Also, we try to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) here.

**Comment by tschm** [comment]
You could reduce the number of warnings 😁 for your actions

**Comment by Caceresenzo** [comment]
The bot created #7 and #8, and the CI still works!
Thanks for your work.

**Comment by tschm** [comment]
I was talking about the warnings in https://github.com/crunchdao/readwrite/actions/runs/8157497845

**Pull request merged**
